package com.yunfie.illustia.settings.store

import androidx.datastore.preferences.core.booleanPreferencesKey
import androidx.datastore.preferences.core.intPreferencesKey
import androidx.datastore.preferences.core.longPreferencesKey
import androidx.datastore.preferences.core.stringPreferencesKey

internal const val LEGACY_PREFS_NAME = "illustia"
internal const val SECURE_PREFS_NAME = "illustia_secure"
internal const val DATASTORE_NAME = "illustia_settings.preferences_pb"
internal const val KEY_REFRESH_TOKEN = "refreshToken"
internal const val KEY_ACCOUNTS = "accounts"
internal const val KEY_ACCOUNT_TOKENS = "accountTokens"
internal const val KEY_ACTIVE_ACCOUNT_INDEX = "activeAccountIndex"
internal const val DEFAULT_OFFLINE_STORAGE_LIMIT_BYTES = 5L * 1024 * 1024 * 1024
internal const val KEY_PIN_HASH = "pinHash"
internal const val KEY_PIN_SALT = "pinSalt"
internal const val KEY_UNLOCK_CODE_HASH = "unlockCodeHash"
internal const val KEY_UNLOCK_CODE_SALT = "unlockCodeSalt"
internal const val PBKDF2_ITERATIONS = 100_000
internal const val PBKDF2_KEY_LENGTH = 256
internal const val KEY_BOOKMARK_USER_ID = "bookmarkUserId"
internal const val KEY_ALLOW_R18 = "allowR18"
internal const val KEY_HIGH_QUALITY = "highQualityImages"
internal const val KEY_BOOKMARK_RESTRICT = "bookmarkRestrict"
internal const val KEY_SEARCH_SORT = "searchSort"
internal const val KEY_SEARCH_TARGET = "searchTarget"
internal const val KEY_SEARCH_DURATION = "searchDuration"
internal const val KEY_SEARCH_BOOKMARK_FILTER = "searchBookmarkFilter"
internal const val KEY_SEARCH_USERS_ENABLED = "searchUsersEnabled"
internal const val KEY_SEARCH_HISTORY = "searchHistory"
internal const val KEY_FAVORITE_TAGS = "favoriteTags"
internal const val KEY_VIEW_HISTORY = "viewHistory"
internal const val KEY_APP_LANGUAGE = "appLanguage"
internal const val KEY_APP_FONT = "appFont"
internal const val KEY_THEME_MODE = "themeMode"
internal const val KEY_USE_DYNAMIC_COLOR = "useDynamicColor"
internal const val KEY_SEED_COLOR = "seedColor"
internal const val KEY_ONBOARDING_SETUP_COMPLETED = "onboardingSetupCompleted"
internal const val KEY_SMOOTH_TRANSITIONS = "smoothTransitions"
internal const val KEY_HAPTIC_MODE = "hapticMode"
internal const val KEY_PREFETCH_IMAGES = "prefetchImages"
internal const val KEY_PIXIV_NETWORK_MODE = "pixivNetworkMode"
internal const val KEY_PIXIV_IMAGE_PROXY_BASE_URL = "pixivImageProxyBaseUrl"
internal const val CURRENT_SETTINGS_VERSION = 10
internal const val HISTORY_SEPARATOR = '\u001F'
internal const val FIELD_SEPARATOR = '\u001E'
internal const val MAX_SEARCH_HISTORY = 6
internal const val MAX_VIEW_HISTORY = 48

internal val SETTINGS_VERSION = intPreferencesKey("settings_version")
internal val BOOKMARK_USER_ID = longPreferencesKey(KEY_BOOKMARK_USER_ID)
internal val APP_LANGUAGE = stringPreferencesKey(KEY_APP_LANGUAGE)
internal val APP_FONT = stringPreferencesKey(KEY_APP_FONT)
internal val THEME_MODE = stringPreferencesKey(KEY_THEME_MODE)
internal val USE_DYNAMIC_COLOR = booleanPreferencesKey(KEY_USE_DYNAMIC_COLOR)
internal val SEED_COLOR = longPreferencesKey(KEY_SEED_COLOR)
internal val ONBOARDING_SETUP_COMPLETED = booleanPreferencesKey(KEY_ONBOARDING_SETUP_COMPLETED)
internal val ALLOW_R18 = booleanPreferencesKey(KEY_ALLOW_R18)
internal val HIGH_QUALITY_IMAGES = booleanPreferencesKey(KEY_HIGH_QUALITY)
internal val BOOKMARK_RESTRICT = stringPreferencesKey(KEY_BOOKMARK_RESTRICT)
internal val SEARCH_SORT = stringPreferencesKey(KEY_SEARCH_SORT)
internal val SEARCH_TARGET = stringPreferencesKey(KEY_SEARCH_TARGET)
internal val SEARCH_DURATION = stringPreferencesKey(KEY_SEARCH_DURATION)
internal val SEARCH_BOOKMARK_FILTER = stringPreferencesKey(KEY_SEARCH_BOOKMARK_FILTER)
internal val SEARCH_USERS_ENABLED = booleanPreferencesKey(KEY_SEARCH_USERS_ENABLED)
internal val SEARCH_HISTORY_JSON = stringPreferencesKey(KEY_SEARCH_HISTORY)
internal val FAVORITE_TAGS_JSON = stringPreferencesKey(KEY_FAVORITE_TAGS)
internal val VIEW_HISTORY_JSON = stringPreferencesKey(KEY_VIEW_HISTORY)
internal val SAVE_VIEW_HISTORY = booleanPreferencesKey("saveViewHistory")
internal val SAVE_SEARCH_HISTORY = booleanPreferencesKey("saveSearchHistory")
internal val APP_LOCK_ENABLED = booleanPreferencesKey("appLockEnabled")
internal val APP_LOCK_TIMING = stringPreferencesKey("appLockTiming")
internal val BIOMETRIC_ENABLED = booleanPreferencesKey("biometricEnabled")
internal val APP_LOCK_FAIL_COUNT = intPreferencesKey("appLockFailCount")
internal val APP_LOCK_COOLDOWN_UNTIL = longPreferencesKey("appLockCooldownUntil")
internal val SMOOTH_TRANSITIONS = booleanPreferencesKey(KEY_SMOOTH_TRANSITIONS)
internal val HAPTIC_MODE = stringPreferencesKey(KEY_HAPTIC_MODE)
internal val PREFETCH_IMAGES = booleanPreferencesKey(KEY_PREFETCH_IMAGES)
internal val AUTO_LOAD_MORE = booleanPreferencesKey("autoLoadMore")
internal val NOTCH_OPTIMIZATION = booleanPreferencesKey("notchOptimization")
internal val CONFIRM_ON_LONG_PRESS_SAVE = booleanPreferencesKey("confirmOnLongPressSave")
internal val DOUBLE_BACK_TO_EXIT = booleanPreferencesKey("doubleBackToExit")
internal val SWIPE_TO_SWITCH_WORKS = booleanPreferencesKey("swipeToSwitchWorks")
internal val SECURE_WINDOW = booleanPreferencesKey("secureWindow")
internal val AMOLED_MODE = booleanPreferencesKey("amoledMode")
internal val SKIP_CONFIRM_ON_DETAIL_SAVE = booleanPreferencesKey("skipConfirmOnDetailSave")
internal val SHOW_AI_BADGE = booleanPreferencesKey("showAiBadge")
internal val FOLLOW_ON_LIKE = booleanPreferencesKey("followOnLike")
internal val PRIVATE_BOOKMARK_DEFAULT = booleanPreferencesKey("privateBookmarkDefault")
internal val AUTO_DOWNLOAD_ON_BOOKMARK = booleanPreferencesKey("autoDownloadOnBookmark")
internal val AUTO_BOOKMARK_ON_DOWNLOAD = booleanPreferencesKey("autoBookmarkOnDownload")
internal val DOWNLOAD_FOLDER_BY_ARTIST = booleanPreferencesKey("downloadFolderByArtist")
internal val DOWNLOAD_FOLDER_BY_WORK = booleanPreferencesKey("downloadFolderByWork")
internal val AUTO_TAG_ON_BOOKMARK = booleanPreferencesKey("autoTagOnBookmark")
internal val SIMULTANEOUS_DOWNLOADS = intPreferencesKey("simultaneousDownloads")
internal val OFFLINE_WIFI_ONLY = booleanPreferencesKey("offlineWifiOnly")
internal val OFFLINE_STORAGE_LIMIT_BYTES = longPreferencesKey("offlineStorageLimitBytes")
internal val FEED_PREVIEW_QUALITY = stringPreferencesKey("feedPreviewQuality")
internal val ILLUST_DETAIL_QUALITY = stringPreferencesKey("illustDetailQuality")
internal val MANGA_DETAIL_QUALITY = stringPreferencesKey("mangaDetailQuality")
internal val FULLSCREEN_QUALITY = stringPreferencesKey("fullscreenQuality")
internal val MANGA_READER_MODE = stringPreferencesKey("mangaReaderMode")
internal val SMART_CACHE_ENABLED = booleanPreferencesKey("smartCacheEnabled")
internal val SMART_CACHE_WIFI_ONLY = booleanPreferencesKey("smartCacheWifiOnly")
internal val SMART_CACHE_ITEM_COUNT = intPreferencesKey("smartCacheItemCount")
internal val IMAGE_CACHE_SIZE_MB = intPreferencesKey("imageCacheSizeMb")
internal val STARTUP_SCREEN = stringPreferencesKey("startupScreen")
internal val USER_PROFILE_BOTTOM_SHEET_ENABLED = booleanPreferencesKey("userProfileBottomSheetEnabled")
internal val SHORTS_FEED_ENABLED = booleanPreferencesKey("shortsFeedEnabled")
internal val DISABLE_HORIZONTAL_SWIPE_IN_SHORTS_FEED = booleanPreferencesKey("disableHorizontalSwipeInShortsFeed")
internal val VERTICAL_COLUMN_COUNT = intPreferencesKey("verticalColumnCount")
internal val HORIZONTAL_COLUMN_COUNT = intPreferencesKey("horizontalColumnCount")
internal val PIXIV_NETWORK_MODE = stringPreferencesKey(KEY_PIXIV_NETWORK_MODE)
internal val PIXIV_IMAGE_PROXY_BASE_URL = stringPreferencesKey(KEY_PIXIV_IMAGE_PROXY_BASE_URL)
internal val MUTED_ILLUSTS_JSON = stringPreferencesKey("mutedIllusts")
internal val MUTED_USERS_JSON = stringPreferencesKey("mutedUsers")
internal val MUTED_TAGS_JSON = stringPreferencesKey("mutedTags")
internal val SEEN_FEED_ILLUSTS_JSON = stringPreferencesKey("seenFeedIllusts")
internal val WALLPAPER_PLAYLIST_ENABLED = booleanPreferencesKey("wallpaperPlaylistEnabled")
internal val ACTIVE_ACCOUNT_INDEX = intPreferencesKey(KEY_ACTIVE_ACCOUNT_INDEX)
internal val PRIVACY_MODE_ENABLED = booleanPreferencesKey("privacyModeEnabled")
internal val PRIVACY_MODE_AUTO_LOCK_TIMING = stringPreferencesKey("privacyModeAutoLockTiming")
internal val HIDE_RECENTS = booleanPreferencesKey("hideRecents")
internal val HIDE_NOTIFICATIONS = booleanPreferencesKey("hideNotifications")
internal val DUMMY_APP_NAME = stringPreferencesKey("dummyAppName")
internal val DUMMY_ICON_VARIANT = stringPreferencesKey("dummyIconVariant")
